### PR TITLE
running integration tests automatically

### PR DESCRIPTION
**Pull request by atrifan**
* support running integration tests automatically for jenkins (with start, clean and stop)

### CODE REVIEW

**Review by corinapurcarea — APPROVED** [review]
👍

**Comment by ddragosd** [comment]
@atrifan what's the motivation for `docker-compose-jenkins.yml` ? Can we not update the existing `docker-compose` and the existing test scripts to work both locally and on Jenkins ?

**Review by ddragosd — CHANGES_REQUESTED** [review]
Can we enable TravisCI or CircleCI as well ?

**Comment by atrifan** [comment]
@ddragosd the thing is like this - for running locally you still need your logs - when you run with jenkins the creation of the folders has some issues with permissions. Another thing is that I don't want to expose ports for jenkins because I want to run in parallel yet for the local machine this might be need for further testing. Regarding TravisCI and CircleCI would be more than great but I think we need to have an enterprise account for this.

**Comment by ddragosd** [comment]
> Regarding TravisCI and CircleCI would be more than great but I think we need to have an enterprise account for this.

For open-source projects a license is not required on either of these.

**Comment by atrifan** [comment]
not needed will migrate to mocka and travis

**Pull request closed without merging**
